apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reporting-service.fullname" . }}
  labels:
{{- include "reporting-service.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "report_files/*").AsConfig | nindent 2 }}